name: rin-lora
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pip
  - pip:
      - accelerate>=0.24.1
      - compel
      - datasets>=2.14
      - pyarrow<14,>=12
      - diffusers>=0.31.0
      - huggingface-hub>=0.23.2
      - peft==0.7.1
      - safetensors
      - transformers==4.36.2
      - xformers
